# Setup
title:        Haoyun
tagline:      A postgraduate student at SUSTech majoring in robotics.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Haoyun Yan
  url:        https://github.com/xtimberlake

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown